### ISSUE TITLE
Improve release process

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/librarian#16]
Current release process:

1. Change package version in `pyproject.toml` following [Semantic Versioning 2.0.0](https://semver.org/#semantic-versioning-200).
2. Commit change and create a git tag: `git tag v0.1.0 && git push origin v0.1.0`. This push will trigger two workflows to publish docker images and Python package.
3. Create the GitHub release from the new tag.

New release process:

1. Create and push the new tag: `git tag v0.1.0 && git push origin v0.1.0`. This event will trigger 3 workflows:

- Publish Docker image (same workflow but triggered pushing a tag)
- Publish Python package (same workflow but triggered pushing a tag)
- Publish GitHub release (new workflow)

For the new workflow we can do something like this:
```
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: steps.check-version.outputs.prerelease == 'true'
```
[From Poetry workflow](https://github.com/python-poetry/poetry/blob/master/.github/workflows/release.yml#L36-L42).

We also want to automatically update the version in the `pyproject.toml` file. THat can be done by using the [Dynamic versioning plugin for Poetry](https://github.com/mtkennerly/poetry-dynamic-versioning). 

We also have to find a way to use the latest commit in the Library project:

https://github.com/Nautilus-Cyberneering/chinese-ideographs/blob/main/.github/workflows/gold-drawings-processing.yml#L28-L41:
```
      - name: Update Librarian submodule
        id: update-librarian
        run: |
          git submodule status
          git submodule update --remote
      - name: Install Librarian with Poetry
        run: |
          cd librarian
          poetry --version
          poetry install
          poetry build
          pip install --user "${{ github.workspace }}/librarian/dist/nautilus_librarian-0.1.0-py3-none-any.whl"
          nautilus-librarian --help
```

I suppose we can get the current version with `poetry version --short`. And the `poetry build` command it's going to build a new package with the latest commit but using the latest released version.

We should also consider https://www.conventionalcommits.org/en/v1.0.0/ since we are not going to create a manual release or CHANGELOG file.
