### ISSUE TITLE
Publish app to PyPI

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/librarian#3]
We could start publishing the app in order to test installation from the Python Package Index:

Main GitHub ACtions available:

- https://github.com/marketplace/actions/publish-python-poetry-package
- https://github.com/marketplace/actions/pypi-publish

We could do the same we do for docker images and publish the package when a new release is created:

```
name: Publish Docker image

#
# Documentation:
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages
#

on:
  release:
    types: [ published ]

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Build Python package
        run: poetry --version && poetry build
    
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
```
